[package]
name = "muse"
version = "0.1.0"
authors = ["Krishan Wyse <kwysek@gmail.com>"]
edition = "2018"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
clap = "2.32"
csv = "1.0"
failure = "0.1"
serde = { version = "1.0", features = ["derive"] }
